#!/bin/sh
#
# Starts pulseaudio.
#

# Create needed directories.
[ -d /var/run/pulse ] || mkdir -p /var/run/pulse
[ -d /var/lib/pulse ] || mkdir -p /var/lib/pulse

start() {
	printf "Starting pulseaudio: "
	umask 077
	/usr/bin/pulseaudio --exit-idle-time=-1 -v &
	echo "OK"
}
stop() {
	printf "Stopping pulseaudio: "
	killall pulseaudio
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

