#!/bin/sh
#
# Start the wifi....
#

case "$1" in
  start)
	printf "Starting wifi: "
	ifconfig wlan0 up
	mkdir -p /var/run/wpa_supplicant
	wpa_supplicant -Dnl80211 -iwlan0 -c /etc/wpa_supplicant.conf -B &
	sleep 1
	wpa_cli -iwlan0 -a/etc/wifi-status -B &
	echo "OK"
	;;
  stop)
	printf "Stopping wifi: "
	killall udhcpc
	sleep 1
	killall wpa_cli
	killall wpa_supplicant
	echo "OK"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

