#!/bin/sh
#
# Start mdev....
#

case "$1" in
  start)
	echo "Starting mdev..."
	mkdir -p /var/run/media/udisk /var/run/media/sdcard
	echo /sbin/mdev >/proc/sys/kernel/hotplug
	/sbin/mdev -s
	echo "mdev done."
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
