#! /bin/sh

case "$1" in
    start)
	echo "Starting goahead."
	/usr/bin/goahead --auth /etc/goahead/auth.txt --route /etc/goahead/route.txt --home / --verbose &
	;;
    stop)
	echo "Stopping goahead."
	killall goahead
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
